// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Microsoft.Extensions.DependencyInjection;
using PMS.Application.IRepositories.Category;
using PMS.Application.IRepositories.Email;
using PMS.Application.IRepositories.ParkingSpace;
using PMS.Application.IRepositories.ResetPasswordLink;
using PMS.Application.IRepositories.Role;
using PMS.Application.IRepositories.User;
using PMS.Infrastructure.Repositories.Category;
using PMS.Infrastructure.Repositories.Email;
using PMS.Infrastructure.Repositories.ParkingSpace;
using PMS.Infrastructure.Repositories.ResetPasswordLink;
using PMS.Infrastructure.Repositories.Role;
using PMS.Infrastructure.Repositories.User;

namespace PMS.Infrastructure.DependencyInjection;

public static class RepositoryServiceInjection
{
    public static IServiceCollection AddRepositories(this IServiceCollection services)
    {
        services.AddScoped<ICategoryRepository, CategoryRepository>();
        services.AddScoped<IEmailRepository, EmailRepository>();
        services.AddScoped<IParkingSpaceRepository, ParkingSpaceRepository>();
        services.AddScoped<IResetPasswordLinkRepository, ResetPasswordLinkRepository>();
        services.AddScoped<IRoleRepository, RoleRepository>();
        services.AddScoped<IUserRepository, UserRepository>();

        return services;
    }
}