// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.ParkingSpace;

public class DeleteParkingSpaceResponse
{
    public string Message { get; set; }
}