// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.


using PMS.Application.Models.Requests.Category;
using PMS.Application.Models.Responses.Common;

namespace PMS.Application.IRepositories.Category;

public interface ICategoryRepository
{

    Task<OperationResponse> AddCategoryAsync(AddCategoryRequest request);


    Task<OperationResponse> DeleteCategoryAsync(DeleteCategoryRequest request);


    Task<OperationResponse> EditCategoryAsync(EditCategoryRequest request);

}