// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.


using PMS.Application.Models.Requests.Email;
using PMS.Application.Models.Responses.Common;

namespace PMS.Application.IRepositories.Email;

public interface IEmailRepository
{

    Task SendEmailAsync(SendEmailRequest request);

}