// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.Role;

public class DeleteRoleRequest
{
    public int RoleId { get; set; }
}