 // <auto-generated />
 // This file was generated by CodeGenerator.
 // Do not modify this file manually.

namespace PMS.Application.Models.Responses.Common;

public class OperationResponse
{
    public string? Message { get; set; }
}
