// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using PMS.Application.Models.Requests;
using PMS.Application.Models.Responses;

namespace PMS.Application.IRepositories.ParkingSpace
{
    public interface IParkingSpaceRepository
    {
        
                    
                            Task<OperationResponse> AddParkingSpaceAsync(AddParkingSpaceRequest request);
                        
                
                    
                            Task<OperationResponse> DeleteParkingSpaceAsync(DeleteParkingSpaceRequest request);
                        
                
                    
                            Task<OperationResponse> EditParkingSpaceAsync(EditParkingSpaceRequest request);
                        
                
    }
}