// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.ResetPasswordLink;

public class GenerateResetPasswordLinkResponse
{
    public string GeneratedLink { get; set; }
    public int? ExpireIn { get; set; }
}