// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.ResetPasswordLink;

public class VerifyResetPasswordLinkResponse
{
    public int? UserId { get; set; }
}