// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.


using PMS.Application.Models.Requests.ResetPasswordLink;
using PMS.Application.Models.Responses.Common;

namespace PMS.Application.IRepositories.ResetPasswordLink;

public interface IResetPasswordLinkRepository
{

    Task<OperationResponse> GenerateResetPasswordLinkAsync(GenerateResetPasswordLinkRequest request);

}