// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Dapper;
using System.Data;
using PMS.Application.IRepositories.ResetPasswordLink;
using PMS.Application.Models.Requests.ResetPasswordLink;
using PMS.Application.Models.Responses.ResetPasswordLink;
using PMS.Application.Models.Responses.Common;

namespace PMS.Infrastructure.Repositories.ResetPasswordLink;

public class ResetPasswordLinkRepository : IResetPasswordLinkRepository
{
    private readonly IDbConnection _connection;

    public ResetPasswordLinkRepository(IDbConnection connection)
    {
        _connection = connection;
    }

    public async Task<GenerateResetPasswordLinkResponse> GenerateResetPasswordLinkAsync(GenerateResetPasswordLinkRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@user_id", request.UserId);

        return await _connection.QueryFirstOrDefaultAsync<GenerateResetPasswordLinkResponse>(
            "usp_generate_reset_password_link",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

}