// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Dapper;
using System.Data;
using PMS.Application.IRepositories.ResetPasswordLink;
using PMS.Application.Models.Requests.ResetPasswordLink;

using PMS.Application.Models.Responses.Common;

namespace PMS.Infrastructure.Repositories.ResetPasswordLink;

public class ResetPasswordLinkRepository : IResetPasswordLinkRepository
{
    private readonly IDbConnection _connection;

    public ResetPasswordLinkRepository(IDbConnection connection)
    {
        _connection = connection;
    }


    public async Task<OperationResponse> GenerateResetPasswordLinkAsync(GenerateResetPasswordLinkRequest request)
    {
        var parameters = new DynamicParameters();

        parameters.Add("@user_name", request.UserName);
        parameters.Add("@base_url", request.BaseUrl);


        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_generate_reset_password_link",
            parameters,
            commandType: CommandType.StoredProcedure);

    }


}