// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.Role;

public class DeleteRoleResponse
{
    public string Message { get; set; }
}