// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Dapper;
using System.Data;
using PMS.Application.IRepositories.Email;
using PMS.Application.Models.Requests.Email;

using PMS.Application.Models.Responses.Common;

namespace PMS.Infrastructure.Repositories.Email;

public class EmailRepository : IEmailRepository
{
    private readonly IDbConnection _connection;

    public EmailRepository(IDbConnection connection)
    {
        _connection = connection;
    }


    public async Task SendEmailAsync(SendEmailRequest request)
    {
        var parameters = new DynamicParameters();

        parameters.Add("@user_email", request.UserEmail);
        parameters.Add("@user_id", request.UserId);
        parameters.Add("@template_id", request.TemplateId);
        parameters.Add("@subject", request.Subject);
        parameters.Add("@body", request.Body);


        await _connection.ExecuteAsync(
            "usp_send_email",
            parameters,
            commandType: CommandType.StoredProcedure);

    }


}