<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Scriban" Version="7.2.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\" />
    <Folder Include="Models\" />
    <Folder Include="Generators\" />
    <Folder Include="Templates\" />
  </ItemGroup>

</Project>
