// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.ParkingSpace;

public class DeleteParkingSpaceRequest
{
    public int ParkingSpaceId { get; set; }
}