// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using PMS.Application.Models.Requests;
using PMS.Application.Models.Responses;

namespace PMS.Application.IRepositories.Role
{
    public interface IRoleRepository
    {
        
                Task<OperationResponse> AddRoleAsync(AddRoleRequest request);
                
                Task<OperationResponse> DeleteRoleAsync(DeleteRoleRequest request);
                
                Task<OperationResponse> EditRoleAsync(EditRoleRequest request);
                
    }
}