// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using PMS.Application.Models.Responses.User;
using PMS.Application.Models.Requests.User;
using PMS.Application.Models.Responses.Common;

namespace PMS.Application.IRepositories.User;

public interface IUserRepository
{
    Task<OperationResponse> AddUserAsync(AddUserRequest request);

    Task<OperationResponse> DeleteUserAsync(DeleteUserRequest request);

    Task<OperationResponse> EditUserAsync(EditUserRequest request);

    Task<GetUserByUsernameResponse> GetUserByUsernameAsync(GetUserByUsernameRequest request);

    Task<LoginUserResponse> LoginUserAsync(LoginUserRequest request);

    Task<OperationResponse> LogoutUserAsync(LogoutUserRequest request);

    Task<OperationResponse> ResetUserPasswordAsync(ResetUserPasswordRequest request);

}