// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using PMS.Application.Models.Requests;
using PMS.Application.Models.Responses;

namespace PMS.Application.IRepositories.User;

public interface IUserRepository
{
    
            
                    Task<OperationResponse> AddUserAsync(AddUserRequest request);
                
        
            
                    Task<OperationResponse> DeleteUserAsync(DeleteUserRequest request);
                
        
            
                    Task<OperationResponse> EditUserAsync(EditUserRequest request);
                
        
            
                    Task<LoginUserResponse> LoginUserAsync(LoginUserRequest request);
                
        
}
