// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Dapper;
using System.Data;
using PMS.Application.IRepositories.ParkingSpace;
using PMS.Application.Models.Requests.ParkingSpace;

using PMS.Application.Models.Responses.Common;

namespace PMS.Infrastructure.Repositories.ParkingSpace;

public class ParkingSpaceRepository : IParkingSpaceRepository
{
    private readonly IDbConnection _connection;

    public ParkingSpaceRepository(IDbConnection connection)
    {
        _connection = connection;
    }

    public async Task<OperationResponse> AddParkingSpaceAsync(AddParkingSpaceRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@floor", request.Floor);
        parameters.Add("@code", request.Code);
        parameters.Add("@parking_space_status_id", request.ParkingSpaceStatusId);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_add_parking_space",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

    public async Task<OperationResponse> DeleteParkingSpaceAsync(DeleteParkingSpaceRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@parking_space_id", request.ParkingSpaceId);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_delete_parking_space",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

    public async Task<OperationResponse> EditParkingSpaceAsync(EditParkingSpaceRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@parking_space_id", request.ParkingSpaceId);
        parameters.Add("@floor", request.Floor);
        parameters.Add("@code", request.Code);
        parameters.Add("@parking_space_status_id", request.ParkingSpaceStatusId);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_edit_parking_space",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

}