// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.Category;

public class DeleteCategoryResponse
{
    public string Message { get; set; }
}