// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.User;

public class AddUserRequest
{
    public string UserName { get; set; }
    public string Password { get; set; }
    public int RoleId { get; set; }
    public string Email { get; set; }
    public string ContactNo { get; set; }
}