// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.User;

public class GetUserByUsernameRequest
{
    public string UserName { get; set; }
}