// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.User;

public class ResetUserPasswordRequest
{
    public Guid Identifier { get; set; }
    public string NewPassword { get; set; }
    public string ConfirmPassword { get; set; }
}