namespace CodeGenerator.Generators
{
    public abstract class BaseGenerator
    {
        protected async Task DeleteOrphanFilesAsync(string outputFolder, HashSet<string> expectedFiles)
        {
            var files = Directory.GetFiles(outputFolder, "*.cs");

            foreach (var file in files)
            {
                var content = await File.ReadAllTextAsync(file);

                if (!content.Contains("This file was generated by CodeGenerator"))
                    continue;

                var fileName = Path.GetFileName(file);

                if (!expectedFiles.Contains(fileName))
                {
                    File.Delete(file);
                    Console.WriteLine($"Deleted: {fileName}");
                }
            }
        }
        protected async Task WriteFileAsync(string filePath, string content)
        {
            if (File.Exists(filePath))
            {
                var existing = await File.ReadAllTextAsync(filePath);

                if (Normalize(existing) == Normalize(content))
                {
                    Console.WriteLine($"Skipped: {Path.GetFileName(filePath)}");
                    return;
                }

                await File.WriteAllTextAsync(filePath, content);
                Console.WriteLine($"Updated: {Path.GetFileName(filePath)}");
            }
            else
            {
                await File.WriteAllTextAsync(filePath, content);
                Console.WriteLine($"Created: {Path.GetFileName(filePath)}");
            }
            
        }
        protected static string Normalize(string text)
        {
            return string.Join(
                Environment.NewLine,
                text.Replace("\r\n", "\n")
                    .Split('\n')
                    .Select(x => x.TrimEnd())
            ).Trim();
        }
    }
}
