// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.ResetPasswordLink;

public class GenerateResetPasswordLinkRequest
{
    public string UserName { get; set; }
    public string BaseUrl { get; set; }
}