// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.ResetPasswordLink;

public class VerifyResetPasswordLinkRequest
{
    public Guid Identifier { get; set; }
}