// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests;

public class AddParkingSpaceRequest
{
    public string Floor { get; set; }
    public string Code { get; set; }
    public int ParkingSpaceStatusId { get; set; }
}