// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests;

public class DeleteParkingSpaceRequstModel
{

    public int ParkingSpaceId { get; set; }

}
