// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests;

public class LoginUserRequest
{

    public string UserName { get; set; }

    public string Password { get; set; }

}
