// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.User;

public class GetUserByUsernameResponse
{
    public int UserId { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
    public string? ContactNo { get; set; }
    public int RoleId { get; set; }
    public string RoleName { get; set; }
}