// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses.User;

public class LogoutUserResponse
{
    public string Message { get; set; }
}