// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.Category;

public class AddCategoryRequest
{
    public string Name { get; set; }
}