// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.Category;

public class EditCategoryRequest
{
    public int CategoryId { get; set; }
    public string Name { get; set; }
}