// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class Billings
{

	public int BillingId { get; set; }

	public int TicketId { get; set; }

	public int PaymentMethodId { get; set; }

	public decimal? Amount { get; set; }

	public DateTime CreatedAt { get; set; }

}