// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class Categories
{

	public int CategoryId { get; set; }

	public string Name { get; set; }

}