// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class EmailLogs
{
    public int EmailLogId { get; set; }
    public int? TemplateId { get; set; }
    public int? UserId { get; set; }
    public string Status { get; set; }
    public DateTime? SendAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public int RetryCount { get; set; }
    public string? ErrorMessage { get; set; }
    public int? ErrorNumber { get; set; }
    public int? MailitemId { get; set; }
    public string? CreatedBy { get; set; }
    public string? ServerName { get; set; }
}