// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class LoginLogs
{
    public int LoginLogId { get; set; }
    public int UserId { get; set; }
    public DateTime LoginAt { get; set; }
    public DateTime? LogoutAt { get; set; }
}