// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class ParkingSpaceStatuses
{

	public int ParkingSpaceStatusId { get; set; }

	public string Name { get; set; }

}