// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class ParkingSpaces
{
    public int ParkingSpaceId { get; set; }
    public string? Floor { get; set; }
    public string Code { get; set; }
    public int ParkingSpaceStatusId { get; set; }
}