// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class PaymentMethods
{

	public int PaymentMethodId { get; set; }

	public string PaymentType { get; set; }

}