// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class ResetPasswordLinks
{
    public int ResetPasswordLinksId { get; set; }
    public int UserId { get; set; }
    public string Link { get; set; }
    public bool? HasUsed { get; set; }
    public DateTime ExpireAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid Identifier { get; set; }
}