// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class Templates
{
    public int TemplateId { get; set; }
    public string Name { get; set; }
    public string Subject { get; set; }
    public string Body { get; set; }
    public bool? IsActive { get; set; }
}