// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Domain.Entities;

public partial class Users
{
    public int UserId { get; set; }
    public int RoleId { get; set; }
    public string UserName { get; set; }
    public string PasswordHash { get; set; }
    public string Email { get; set; }
    public string? ContactNo { get; set; }
    public bool? IsActive { get; set; }
}