// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

using Dapper;
using System.Data;
using PMS.Application.IRepositories.Role;
using PMS.Application.Models.Requests.Role;

using PMS.Application.Models.Responses.Common;

namespace PMS.Infrastructure.Repositories.Role;

public class RoleRepository : IRoleRepository
{
    private readonly IDbConnection _connection;

    public RoleRepository(IDbConnection connection)
    {
        _connection = connection;
    }

    public async Task<OperationResponse> AddRoleAsync(AddRoleRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@name", request.Name);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_add_role",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

    public async Task<OperationResponse> DeleteRoleAsync(DeleteRoleRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@role_id", request.RoleId);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_delete_role",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

    public async Task<OperationResponse> EditRoleAsync(EditRoleRequest request)
    {
        var parameters = new DynamicParameters();
        parameters.Add("@role_id", request.RoleId);
        parameters.Add("@name", request.Name);

        return await _connection.QueryFirstOrDefaultAsync<OperationResponse>(
            "usp_edit_role",
            parameters,
            commandType: CommandType.StoredProcedure);
    }

}