// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests;

public class LoginUserResponse
{

    public int? UserId { get; set; }

    public string? UserName { get; set; }

    public int? RoleId { get; set; }

    public string? RoleName { get; set; }

}
