// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Responses;

public class OperationResponse
{
    public string Message { get; set; } = string.Empty;
}
