// <auto-generated />
// This file was generated by CodeGenerator.
// Do not modify this file manually.

namespace PMS.Application.Models.Requests.Email;

public class SendEmailRequest
{
    public string UserEmail { get; set; }
    public int UserId { get; set; }
    public int TemplateId { get; set; }
    public string Subject { get; set; }
    public string Body { get; set; }
}